language: php
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- nightly
env:
  matrix:
  - DB=mysql
matrix:
  allow_failures:
  - php: nightly
before_deploy:
- zip -r plg_vm_unpurchased.zip plg_vm_unpurchased/src -x \*.git\* *.gitattributes*
deploy:
  provider: releases
  file:
  - plg_vm_unpurchased.zip
  skip_cleanup: true
  on:
    tags: true
  api_key: $GITHUB_TOKEN
after_deploy:
  - curl -T plg_vm_unpurchased/plg_vm_unpurchased_updates.xml -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
